### ISSUE TITLE
Memory Corruption when running tests

### ISSUE THREAD

**Issue by CryZe** [kyren/luster#1]
I just checked out this project and it seems like there's a memory corruption happening when running the tests. I'm not sure you are aware of that, so I'm just letting you know in case.
```
Critical error detected c0000374
Exception thrown at 0x00007FFC01204D1B (ntdll.dll) in basic-66257f80e6d12447.exe: 0xC0000374: Ein Heap wurde beschädigt (parameters: 0x00007FFC012697B0).
```

**Comment by CryZe** [comment]
It seems to be happen fairly late, so I'd say it's happening in the some Drop implementation.

**Comment by kyren** [comment]
oh that's good to know, I'll try it on windows and see.  It pretty much has to be a bug in the gc-arena code, that should be fun to debug.

**Comment by kyren** [comment]
Oh, I bet I know what it is without looking, this is an easy one.

**Comment by kyren** [comment]
It was hopefully just the drop order on arena types, which I actually something I remember acknowledging that I had to do I just managed somehow to forget to do it.

**Comment by kyren** [comment]
In any case thanks for looking at my very very very very early project.

**Comment by kyren** [comment]
Actually I take that back what I said, I need to debug the garbage collection system some more, clearly something is causing heap corruption for me now as well and causing jemalloc operations to hang.

**Comment by kyren** [comment]
Okay NOW this should definitely be fixed, whichever one of the 3 or 4 ridiculous bugs was causing it.

**Comment by CryZe** [comment]
It seems to work now :D
